### PR TITLE
Fixes #40 (v1.1.18 no longer builds on CentOS/RHEL/Oracle Linux 7)

### LINKED ISSUE #40: v1.1.18 no longer builds on CentOS 7 / RHEL 7 / Oracle Linux 7
Here is the error message output, it was working fine up until today (I.E. <= `v1.1.17`):
```
unixlauncher.cpp:79:53: error: ‘popen’ was not declared in this scope
             fp = popen("/usr/libexec/java_home", "r");
                                                     ^
unixlauncher.cpp:81:43: error: ‘fgets’ was not declared in this scope
                 fgets(tmp, sizeof(tmp), fp);
                                           ^
unixlauncher.cpp:84:26: error: ‘pclose’ was not declared in this scope
                 pclose(fp);
```

This appears to have been caused by this new code:
https://github.com/jruby/jruby-launcher/pull/38

Steps to reproduce:
```shell
$ # Working with `Debian buster` and `v1.1.18`
$ docker run --rm openjdk:8 bash -c 'apt-get update; apt-get -y install build-essential; git clone https://github.com/rbenv/rbenv.git /usr/local/rbenv; mkdir -p /usr/local/rbenv/plugins; git clone https://github.com/rbenv/ruby-build.git /usr/local/rbenv/plugins/ruby-build; export RBENV_ROOT=/usr/local/rbenv; export PATH="$RBENV_ROOT/bin:$PATH"; eval "$(${RBENV_ROOT}/bin/rbenv init -)"; rbenv install jruby-9.2.19.0 || cat /tmp/ruby-build*;'

$ # Not working with `Oracle Linux 7` and `v1.1.18`
$ docker run --rm openjdk:8-oraclelinux7 bash -c 'yum -y groups install "Development Tools"; git clone https://github.com/rbenv/rbenv.git /usr/local/rbenv; mkdir -p /usr/local/rbenv/plugins; git clone https://github.com/rbenv/ruby-build.git /usr/local/rbenv/plugins/ruby-build; export RBENV_ROOT=/usr/local/rbenv; export PATH="$RBENV_ROOT/bin:$PATH"; eval "$(${RBENV_ROOT}/bin/rbenv init -)"; rbenv install jruby-9.2.19.0 || cat /tmp/ruby-build*;'

$ # Working with `Oracle Linux 7` and `v1.1.17`
$ docker run --rm openjdk:8-oraclelinux7 bash -c 'yum -y groups install "Development Tools"; git clone https://github.com/rbenv/rbenv.git /usr/local/rbenv; mkdir -p /usr/local/rbenv/plugins; git clone https://github.com/rbenv/ruby-build.git /usr/local/rbenv/plugins/ruby-build; export RBENV_ROOT=/usr/local/rbenv; export PATH="$RBENV_ROOT/bin:$PATH"; eval "$(${RBENV_ROOT}/bin/rbenv init -)"; sed -i \'1iinstall_jruby_launcher() {\n  cd "${PREFIX_PATH}/bin"\n  { ./ruby gem install jruby-launcher --version 1.1.17\n  } >&4 2>&1\n}\' /usr/local/rbenv/plugins/ruby-build/share/ruby-build/jruby-9.2.19.0; rbenv install jruby-9.2.19.0 || cat /tmp/ruby-build*;'
```

### PR DESCRIPTION
**Pull request by hummeltech**
Missing `<stdio.h>` include in `unixlauncher.cpp`:

Before:
```shell
$ make
make -f inc/Makefile-rules.mk CONF=unix SUBPROJECTS= .build-conf
make[1]: Entering directory `/home/ec2-user/jruby-launcher'
make -f inc/Makefile-rules.mk jruby
make[2]: Entering directory `/home/ec2-user/jruby-launcher'
mkdir -p build/unix/Linux
rm -f build/unix/Linux/argparser.o.d
g++ -O2 -Wall  -DJRUBY_MODULE=1   -c argparser.cpp -MMD -MP -MF build/unix/Linux/argparser.o.d -o build/unix/Linux/argparser.o
mkdir -p build/unix/Linux
rm -f build/unix/Linux/utilsfuncs.o.d
g++ -O2 -Wall  -DJRUBY_MODULE=1   -c utilsfuncs.cpp -MMD -MP -MF build/unix/Linux/utilsfuncs.o.d -o build/unix/Linux/utilsfuncs.o
mkdir -p build/unix/Linux
rm -f build/unix/Linux/ng.o.d
cc -O2 -Wall  -DJRUBY_MODULE=1   -c ng.c -MMD -MP -MF build/unix/Linux/ng.o.d -o build/unix/Linux/ng.o
mkdir -p build/unix/Linux
rm -f build/unix/Linux/strlcpy.o.d
cc -O2 -Wall  -DJRUBY_MODULE=1   -c strlcpy.c -MMD -MP -MF build/unix/Linux/strlcpy.o.d -o build/unix/Linux/strlcpy.o
mkdir -p build/unix/Linux
rm -f build/unix/Linux/jrubyexe.o.d
g++ -O2 -Wall  -DJRUBY_MODULE=1   -c jrubyexe.cpp -MMD -MP -MF build/unix/Linux/jrubyexe.o.d -o build/unix/Linux/jrubyexe.o
mkdir -p build/unix/Linux
rm -f build/unix/Linux/unixlauncher.o.d
g++ -O2 -Wall  -DJRUBY_MODULE=1   -c unixlauncher.cpp -MMD -MP -MF build/unix/Linux/unixlauncher.o.d -o build/unix/Linux/unixlauncher.o
unixlauncher.cpp: In member function ‘int UnixLauncher::run(int, char**, char**)’:
unixlauncher.cpp:51:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (java.find_last_of('/') == -1) {
                                        ^
unixlauncher.cpp:80:44: error: ‘popen’ was not declared in this scope
             fp = popen(javaHomeCommand, "r");
                                            ^
unixlauncher.cpp:82:43: error: ‘fgets’ was not declared in this scope
                 fgets(tmp, sizeof(tmp), fp);
                                           ^
unixlauncher.cpp:85:26: error: ‘pclose’ was not declared in this scope
                 pclose(fp);
                          ^
make[2]: *** [build/unix/Linux/unixlauncher.o] Error 1
make[2]: Leaving directory `/home/ec2-user/jruby-launcher'
make[1]: *** [.build-conf] Error 2
make[1]: Leaving directory `/home/ec2-user/jruby-launcher'
make: *** [.build-impl] Error 2
```

After:
```shell
$ make
make -f inc/Makefile-rules.mk CONF=unix SUBPROJECTS= .build-conf
make[1]: Entering directory `/home/ec2-user/jruby-launcher'
make -f inc/Makefile-rules.mk jruby
make[2]: Entering directory `/home/ec2-user/jruby-launcher'
mkdir -p build/unix/Linux
rm -f build/unix/Linux/argparser.o.d
g++ -O2 -Wall  -DJRUBY_MODULE=1   -c argparser.cpp -MMD -MP -MF build/unix/Linux/argparser.o.d -o build/unix/Linux/argparser.o
mkdir -p build/unix/Linux
rm -f build/unix/Linux/utilsfuncs.o.d
g++ -O2 -Wall  -DJRUBY_MODULE=1   -c utilsfuncs.cpp -MMD -MP -MF build/unix/Linux/utilsfuncs.o.d -o build/unix/Linux/utilsfuncs.o
mkdir -p build/unix/Linux
rm -f build/unix/Linux/ng.o.d
cc -O2 -Wall  -DJRUBY_MODULE=1   -c ng.c -MMD -MP -MF build/unix/Linux/ng.o.d -o build/unix/Linux/ng.o
mkdir -p build/unix/Linux
rm -f build/unix/Linux/strlcpy.o.d
cc -O2 -Wall  -DJRUBY_MODULE=1   -c strlcpy.c -MMD -MP -MF build/unix/Linux/strlcpy.o.d -o build/unix/Linux/strlcpy.o
mkdir -p build/unix/Linux
rm -f build/unix/Linux/jrubyexe.o.d
g++ -O2 -Wall  -DJRUBY_MODULE=1   -c jrubyexe.cpp -MMD -MP -MF build/unix/Linux/jrubyexe.o.d -o build/unix/Linux/jrubyexe.o
mkdir -p build/unix/Linux
rm -f build/unix/Linux/unixlauncher.o.d
g++ -O2 -Wall  -DJRUBY_MODULE=1   -c unixlauncher.cpp -MMD -MP -MF build/unix/Linux/unixlauncher.o.d -o build/unix/Linux/unixlauncher.o
unixlauncher.cpp: In member function ‘int UnixLauncher::run(int, char**, char**)’:
unixlauncher.cpp:52:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (java.find_last_of('/') == -1) {
                                        ^
g++ -O2 -Wall  -DJRUBY_MODULE=1    -o build/unix/Linux/jruby-launcher build/unix/Linux/argparser.o build/unix/Linux/utilsfuncs.o build/unix/Linux/ng.o build/unix/Linux/strlcpy.o build/unix/Linux/jrubyexe.o build/unix/Linux/unixlauncher.o -lstdc++
cp build/unix/Linux/jruby-launcher jruby
make[2]: Leaving directory `/home/ec2-user/jruby-launcher'
make[1]: Leaving directory `/home/ec2-user/jruby-launcher'
```

### CODE REVIEW

**Comment by hummeltech** [comment]
Fixes #40

**Comment by hummeltech** [comment]
I also added some more build tests in #42

**Comment by headius** [comment]
Thank you!
