### ISSUE TITLE
v1.1.18 no longer builds on CentOS 7 / RHEL 7 / Oracle Linux 7

### ISSUE THREAD

**Issue by hummeltech** [jruby/jruby-launcher#40]
Here is the error message output, it was working fine up until today (I.E. <= `v1.1.17`):
```
unixlauncher.cpp:79:53: error: ‘popen’ was not declared in this scope
             fp = popen("/usr/libexec/java_home", "r");
                                                     ^
unixlauncher.cpp:81:43: error: ‘fgets’ was not declared in this scope
                 fgets(tmp, sizeof(tmp), fp);
                                           ^
unixlauncher.cpp:84:26: error: ‘pclose’ was not declared in this scope
                 pclose(fp);
```

This appears to have been caused by this new code:
https://github.com/jruby/jruby-launcher/pull/38

Steps to reproduce:
```shell
$ # Working with `Debian buster` and `v1.1.18`
$ docker run --rm openjdk:8 bash -c 'apt-get update; apt-get -y install build-essential; git clone https://github.com/rbenv/rbenv.git /usr/local/rbenv; mkdir -p /usr/local/rbenv/plugins; git clone https://github.com/rbenv/ruby-build.git /usr/local/rbenv/plugins/ruby-build; export RBENV_ROOT=/usr/local/rbenv; export PATH="$RBENV_ROOT/bin:$PATH"; eval "$(${RBENV_ROOT}/bin/rbenv init -)"; rbenv install jruby-9.2.19.0 || cat /tmp/ruby-build*;'

$ # Not working with `Oracle Linux 7` and `v1.1.18`
$ docker run --rm openjdk:8-oraclelinux7 bash -c 'yum -y groups install "Development Tools"; git clone https://github.com/rbenv/rbenv.git /usr/local/rbenv; mkdir -p /usr/local/rbenv/plugins; git clone https://github.com/rbenv/ruby-build.git /usr/local/rbenv/plugins/ruby-build; export RBENV_ROOT=/usr/local/rbenv; export PATH="$RBENV_ROOT/bin:$PATH"; eval "$(${RBENV_ROOT}/bin/rbenv init -)"; rbenv install jruby-9.2.19.0 || cat /tmp/ruby-build*;'

$ # Working with `Oracle Linux 7` and `v1.1.17`
$ docker run --rm openjdk:8-oraclelinux7 bash -c 'yum -y groups install "Development Tools"; git clone https://github.com/rbenv/rbenv.git /usr/local/rbenv; mkdir -p /usr/local/rbenv/plugins; git clone https://github.com/rbenv/ruby-build.git /usr/local/rbenv/plugins/ruby-build; export RBENV_ROOT=/usr/local/rbenv; export PATH="$RBENV_ROOT/bin:$PATH"; eval "$(${RBENV_ROOT}/bin/rbenv init -)"; sed -i \'1iinstall_jruby_launcher() {\n  cd "${PREFIX_PATH}/bin"\n  { ./ruby gem install jruby-launcher --version 1.1.17\n  } >&4 2>&1\n}\' /usr/local/rbenv/plugins/ruby-build/share/ruby-build/jruby-9.2.19.0; rbenv install jruby-9.2.19.0 || cat /tmp/ruby-build*;'
```

**Comment by hummeltech** [comment]
@headius have you run into this issue on any RHEL 7 systems?

**Comment by edgeworthch** [comment]
I'm also seeing failures on amazonlinux-2017.09

**Comment by headius** [comment]
@hummeltech No but I did have to mess around with the includes after pushing from MacOS to Linux CI (Debian-based). If your commit above works then toss it in a quick PR and I'll merge and release.

**Comment by headius** [comment]
I say "no" as in "I have not tried this on RHEL". C is so picky!

**Comment by hummeltech** [comment]
Yeah, sorry about that, I already created a pull request, I think it's only linking the commit because it was referenced in the commit message.

Here's the pull request:
#41

**Comment by headius** [comment]
jruby-launcher 1.1.19 is released! Thanks for the help!
